services:
  whisper-gpu:
    build: .
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/root/.cache/whisper
      - ./audio-files:/app
    command: >
      whisper audio-file.mp3
      --device cuda
      --model turbo
      --language Italian
      --output_dir /app
      --output_format txt

  whisper-cpu:
    build: .
    profiles:
      - cpu
    volumes:
      - ./models:/root/.cache/whisper
      - ./audio-files:/app
    command: >
      whisper audio-file.mp3
      --model turbo
      --language Italian
      --output_dir /app
      --output_format txt
